#! /bin/bash

## Loading parameters from the previous script.
REPLICASDIR=$1
i=$2
EXP=$3
NUMREPLICAS=$4
GENOME=$5
INSDIR=$6
PEAK=$7

## Processing the specified sample.
echo ""
echo "========================"
echo "| PROCESSING SAMPLE $i |"
echo "========================"
echo ""

cd ${REPLICASDIR} 

## Sample quality control and mapping reads to the reference genome.
cd chip
if [ -f sample_chip_${i}_2.fq.gz ]
then
   fastqc sample_chip_{$i}_1.fq.gz
   fastqc sample_chip_{$i}_2.fq.gz
   bowtie2 -x ../../../genome/index -1 sample_chip_{$i}_1.fq.gz -2 sample_chip_{$i}_2.fq.gz -S chip_$i.sam 2> stats_chip_$i.txt  
else
   fastqc sample_chip_$i.fq.gz
   bowtie2 -x ../../../genome/index -U sample_chip_$i.fq.gz -S chip_$i.sam 2> stats_chip_$i.txt
fi

cd ../input
if [ -f sample_input_${i}_2.fq.gz ]
then
   fastqc sample_input_{$i}_1.fq.gz
   fastqc sample_input_{$i}_2.fq.gz
   bowtie2 -x ../../../genome/index -1 sample_input_{$i}_1.fq.gz -2 sample_input_{$i}_2.fq.gz -S input_$i.sam 2> stats_input_$i.txt
   
else
   fastqc sample_input_$i.fq.gz
   bowtie2 -x ../../../genome/index -U sample_input_$i.fq.gz -S input_$i.sam 2> stats_input_$i.txt
fi
cd ..

## Generating sorted bam file.
cd chip
samtools sort -o chip_$i.bam chip_$i.sam
rm chip_$i.sam
samtools index chip_$i.bam
cd ../input
samtools sort -o input_$i.bam input_$i.sam
rm input_$i.sam
samtools index input_$i.bam
cd ..
  
## Peak calling.
cd replica_results

if [ $PEAK -eq 1 ]
then
  macs2 callpeak -t ../chip/chip_$i.bam -c ../input/input_$i.bam -f BAM --outdir . -n $i
  
elif [ $PEAK -eq 2 ]
then
  macs2 callpeak --broad -t ../chip/chip_$i.bam -c ../input/input_$i.bam -f BAM --outdir . -n $i
fi

echo "Peak calling done!"
cd ../../..
echo ""
echo "==================="
echo "| REPLICA $i DONE |"
echo "==================="
echo ""

